# Generated by Django 5.0.7 on 2024-07-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0002_alter_food_options_alter_foodsfield_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={},
        ),
        migrations.AlterModelOptions(
            name='foodsfield',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sectionfood',
            options={},
        ),
    ]
